services:
  - type: web
    name: data-analyst-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -w 2 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4
      - key: DEBUG
        value: false
      - key: PYTHONPATH
        value: .
    healthCheckPath: /health
